version: "3"
services:
  api-db:
    image: mongo:4.4.1
    container_name: "api-db"
    ports:
      - 27017:27017

  api:
    build:
      context: .
    ports:
      - 8081:8081
    links:
      - api-db
    depends_on:
      - api-db